In [0]:
# !pip uninstall tensorflow
# !pip install tensorflow==2.0.0

In [0]:
%matplotlib inline

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy, SparseCategoricalCrossentropy
from tensorflow.keras.metrics import Accuracy, SparseCategoricalAccuracy

from tensorflow.keras.datasets import mnist


In [16]:
tf.__version__

'2.0.0'

# Training And Improving Neural Networks

In [5]:
(train_attributes, train_labels), (test_attributes, test_labels) = mnist.load_data()
train_attributes, test_attributes = train_attributes / 255.0, test_attributes / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [6]:
model = Sequential([
                    Input(shape=(28, 28)), 
                    Flatten(),
                    Dense(20, activation="relu", kernel_regularizer="l2"), # bias_regularizer="l2", activity_regularizer="l2"
                    Dropout(0.2),
                    Dense(10, activation="relu", kernel_regularizer="l2"),
                    Dropout(0.2),
                    Dense(10, activation="softmax", kernel_regularizer="l2")
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 20)                15700     
_________________________________________________________________
dropout (Dropout)            (None, 20)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                210       
_________________________________________________________________
dropout_1 (Dropout)          (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                110       
Total params: 16,020
Trainable params: 16,020
Non-trainable params: 0
____________________________________________________

In [17]:
model.layers[1].bias.numpy()

array([ 0.01568719,  0.99120075,  0.6458965 , -0.03011058,  0.20457084,
        0.5300341 ,  0.5356678 , -0.08842864,  0.09301498, -0.2126035 ,
        0.38955343,  0.44308993,  0.67265546, -0.5065299 , -0.22790423,
        0.20084251,  0.65979004, -0.01776373,  0.06518698, -0.19207826],
      dtype=float32)

In [8]:
model.layers[1].kernel.numpy().shape

(784, 20)

In [9]:
model.layers[1].weights

[<tf.Variable 'dense/kernel:0' shape=(784, 20) dtype=float32, numpy=
 array([[-5.1934503e-02,  4.5019671e-02, -7.5636007e-02, ...,
         -3.5177082e-02,  8.0220297e-02, -2.0024069e-02],
        [ 3.7844829e-02,  6.3456818e-02, -3.8798951e-02, ...,
          3.9384514e-03,  5.8052957e-02, -7.6568007e-02],
        [ 7.1279764e-02,  2.7924202e-02,  2.8612532e-02, ...,
          8.1798494e-02, -5.7039648e-02, -2.3152016e-02],
        ...,
        [ 5.8114529e-06, -6.1160810e-02,  1.8731326e-02, ...,
          7.8566596e-03,  2.6911303e-02,  2.8279878e-02],
        [-6.5620840e-03, -1.9114204e-02,  2.8266244e-02, ...,
          4.0882424e-02, -6.9884732e-02,  4.7723085e-02],
        [-3.1820845e-02,  3.9124981e-02,  1.8236682e-02, ...,
          2.8599076e-02, -1.5188672e-02, -4.7633763e-02]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(20,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.], dtype=float32)>]

In [0]:
model.compile(optimizer=Adam(learning_rate=0.001), loss=SparseCategoricalCrossentropy(), metrics=[SparseCategoricalAccuracy()])# "accuracy"

In [18]:
model.fit(train_attributes, train_labels, epochs=10, batch_size=16)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 7s 109us/sample - loss: 1.1461 - sparse_categorical_accuracy: 0.7614
Epoch 2/10
60000/60000 [==============================] - 6s 105us/sample - loss: 1.1481 - sparse_categorical_accuracy: 0.7604
Epoch 3/10
60000/60000 [==============================] - 6s 104us/sample - loss: 1.1553 - sparse_categorical_accuracy: 0.7563
Epoch 4/10
60000/60000 [==============================] - 6s 106us/sample - loss: 1.1479 - sparse_categorical_accuracy: 0.7605
Epoch 5/10
60000/60000 [==============================] - 6s 103us/sample - loss: 1.1495 - sparse_categorical_accuracy: 0.7603
Epoch 6/10
60000/60000 [==============================] - 6s 103us/sample - loss: 1.1463 - sparse_categorical_accuracy: 0.7603
Epoch 7/10
60000/60000 [==============================] - 6s 104us/sample - loss: 1.1442 - sparse_categorical_accuracy: 0.7612
Epoch 8/10
60000/60000 [==============================] - 6s 105us/sample - loss: 1.1392

In [12]:
print(model.predict_classes(train_attributes[:10]))
print(train_labels[:10])

[3 0 4 1 9 2 1 3 1 4]
[5 0 4 1 9 2 1 3 1 4]
